// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/collab/collab.proto

package collab

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDocStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         string                 `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocStateRequest) Reset() {
	*x = GetDocStateRequest{}
	mi := &file_proto_collab_collab_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocStateRequest) ProtoMessage() {}

func (x *GetDocStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collab_collab_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocStateRequest.ProtoReflect.Descriptor instead.
func (*GetDocStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_collab_collab_proto_rawDescGZIP(), []int{0}
}

func (x *GetDocStateRequest) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

type DocState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         string                 `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Snapshot      []byte                 `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Version       uint64                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocState) Reset() {
	*x = DocState{}
	mi := &file_proto_collab_collab_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocState) ProtoMessage() {}

func (x *DocState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collab_collab_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocState.ProtoReflect.Descriptor instead.
func (*DocState) Descriptor() ([]byte, []int) {
	return file_proto_collab_collab_proto_rawDescGZIP(), []int{1}
}

func (x *DocState) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *DocState) GetSnapshot() []byte {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *DocState) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetCollaboratorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         string                 `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCollaboratorsRequest) Reset() {
	*x = GetCollaboratorsRequest{}
	mi := &file_proto_collab_collab_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollaboratorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollaboratorsRequest) ProtoMessage() {}

func (x *GetCollaboratorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collab_collab_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollaboratorsRequest.ProtoReflect.Descriptor instead.
func (*GetCollaboratorsRequest) Descriptor() ([]byte, []int) {
	return file_proto_collab_collab_proto_rawDescGZIP(), []int{2}
}

func (x *GetCollaboratorsRequest) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

type CollaboratorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collaborators []*Collaborator        `protobuf:"bytes,1,rep,name=collaborators,proto3" json:"collaborators,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollaboratorsResponse) Reset() {
	*x = CollaboratorsResponse{}
	mi := &file_proto_collab_collab_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollaboratorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollaboratorsResponse) ProtoMessage() {}

func (x *CollaboratorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collab_collab_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollaboratorsResponse.ProtoReflect.Descriptor instead.
func (*CollaboratorsResponse) Descriptor() ([]byte, []int) {
	return file_proto_collab_collab_proto_rawDescGZIP(), []int{3}
}

func (x *CollaboratorsResponse) GetCollaborators() []*Collaborator {
	if x != nil {
		return x.Collaborators
	}
	return nil
}

type Collaborator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Collaborator) Reset() {
	*x = Collaborator{}
	mi := &file_proto_collab_collab_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Collaborator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Collaborator) ProtoMessage() {}

func (x *Collaborator) ProtoReflect() protoreflect.Message {
	mi := &file_proto_collab_collab_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Collaborator.ProtoReflect.Descriptor instead.
func (*Collaborator) Descriptor() ([]byte, []int) {
	return file_proto_collab_collab_proto_rawDescGZIP(), []int{4}
}

func (x *Collaborator) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Collaborator) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Collaborator) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

var File_proto_collab_collab_proto protoreflect.FileDescriptor

const file_proto_collab_collab_proto_rawDesc = "" +
	"\n" +
	"\x19proto/collab/collab.proto\x12\x06collab\"+\n" +
	"\x12GetDocStateRequest\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\tR\x05docId\"W\n" +
	"\bDocState\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\tR\x05docId\x12\x1a\n" +
	"\bsnapshot\x18\x02 \x01(\fR\bsnapshot\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\"0\n" +
	"\x17GetCollaboratorsRequest\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\tR\x05docId\"S\n" +
	"\x15CollaboratorsResponse\x12:\n" +
	"\rcollaborators\x18\x01 \x03(\v2\x14.collab.CollaboratorR\rcollaborators\"Y\n" +
	"\fCollaborator\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color2\xa0\x01\n" +
	"\rCollabService\x12;\n" +
	"\vGetDocState\x12\x1a.collab.GetDocStateRequest\x1a\x10.collab.DocState\x12R\n" +
	"\x10GetCollaborators\x12\x1f.collab.GetCollaboratorsRequest\x1a\x1d.collab.CollaboratorsResponseB*Z(github.com/spike/goTogether/proto/collabb\x06proto3"

var (
	file_proto_collab_collab_proto_rawDescOnce sync.Once
	file_proto_collab_collab_proto_rawDescData []byte
)

func file_proto_collab_collab_proto_rawDescGZIP() []byte {
	file_proto_collab_collab_proto_rawDescOnce.Do(func() {
		file_proto_collab_collab_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_collab_collab_proto_rawDesc), len(file_proto_collab_collab_proto_rawDesc)))
	})
	return file_proto_collab_collab_proto_rawDescData
}

var file_proto_collab_collab_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_collab_collab_proto_goTypes = []any{
	(*GetDocStateRequest)(nil),      // 0: collab.GetDocStateRequest
	(*DocState)(nil),                // 1: collab.DocState
	(*GetCollaboratorsRequest)(nil), // 2: collab.GetCollaboratorsRequest
	(*CollaboratorsResponse)(nil),   // 3: collab.CollaboratorsResponse
	(*Collaborator)(nil),            // 4: collab.Collaborator
}
var file_proto_collab_collab_proto_depIdxs = []int32{
	4, // 0: collab.CollaboratorsResponse.collaborators:type_name -> collab.Collaborator
	0, // 1: collab.CollabService.GetDocState:input_type -> collab.GetDocStateRequest
	2, // 2: collab.CollabService.GetCollaborators:input_type -> collab.GetCollaboratorsRequest
	1, // 3: collab.CollabService.GetDocState:output_type -> collab.DocState
	3, // 4: collab.CollabService.GetCollaborators:output_type -> collab.CollaboratorsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_collab_collab_proto_init() }
func file_proto_collab_collab_proto_init() {
	if File_proto_collab_collab_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_collab_collab_proto_rawDesc), len(file_proto_collab_collab_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_collab_collab_proto_goTypes,
		DependencyIndexes: file_proto_collab_collab_proto_depIdxs,
		MessageInfos:      file_proto_collab_collab_proto_msgTypes,
	}.Build()
	File_proto_collab_collab_proto = out.File
	file_proto_collab_collab_proto_goTypes = nil
	file_proto_collab_collab_proto_depIdxs = nil
}
