// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/collab/collab.proto

package collab

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CollabService_GetDocState_FullMethodName      = "/collab.CollabService/GetDocState"
	CollabService_GetCollaborators_FullMethodName = "/collab.CollabService/GetCollaborators"
)

// CollabServiceClient is the client API for CollabService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CollabServiceClient interface {
	GetDocState(ctx context.Context, in *GetDocStateRequest, opts ...grpc.CallOption) (*DocState, error)
	GetCollaborators(ctx context.Context, in *GetCollaboratorsRequest, opts ...grpc.CallOption) (*CollaboratorsResponse, error)
}

type collabServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCollabServiceClient(cc grpc.ClientConnInterface) CollabServiceClient {
	return &collabServiceClient{cc}
}

func (c *collabServiceClient) GetDocState(ctx context.Context, in *GetDocStateRequest, opts ...grpc.CallOption) (*DocState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocState)
	err := c.cc.Invoke(ctx, CollabService_GetDocState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collabServiceClient) GetCollaborators(ctx context.Context, in *GetCollaboratorsRequest, opts ...grpc.CallOption) (*CollaboratorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollaboratorsResponse)
	err := c.cc.Invoke(ctx, CollabService_GetCollaborators_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CollabServiceServer is the server API for CollabService service.
// All implementations must embed UnimplementedCollabServiceServer
// for forward compatibility.
type CollabServiceServer interface {
	GetDocState(context.Context, *GetDocStateRequest) (*DocState, error)
	GetCollaborators(context.Context, *GetCollaboratorsRequest) (*CollaboratorsResponse, error)
	mustEmbedUnimplementedCollabServiceServer()
}

// UnimplementedCollabServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCollabServiceServer struct{}

func (UnimplementedCollabServiceServer) GetDocState(context.Context, *GetDocStateRequest) (*DocState, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDocState not implemented")
}
func (UnimplementedCollabServiceServer) GetCollaborators(context.Context, *GetCollaboratorsRequest) (*CollaboratorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCollaborators not implemented")
}
func (UnimplementedCollabServiceServer) mustEmbedUnimplementedCollabServiceServer() {}
func (UnimplementedCollabServiceServer) testEmbeddedByValue()                       {}

// UnsafeCollabServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CollabServiceServer will
// result in compilation errors.
type UnsafeCollabServiceServer interface {
	mustEmbedUnimplementedCollabServiceServer()
}

func RegisterCollabServiceServer(s grpc.ServiceRegistrar, srv CollabServiceServer) {
	// If the following call panics, it indicates UnimplementedCollabServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CollabService_ServiceDesc, srv)
}

func _CollabService_GetDocState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollabServiceServer).GetDocState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollabService_GetDocState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollabServiceServer).GetDocState(ctx, req.(*GetDocStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CollabService_GetCollaborators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCollaboratorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollabServiceServer).GetCollaborators(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CollabService_GetCollaborators_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollabServiceServer).GetCollaborators(ctx, req.(*GetCollaboratorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CollabService_ServiceDesc is the grpc.ServiceDesc for CollabService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CollabService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "collab.CollabService",
	HandlerType: (*CollabServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDocState",
			Handler:    _CollabService_GetDocState_Handler,
		},
		{
			MethodName: "GetCollaborators",
			Handler:    _CollabService_GetCollaborators_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/collab/collab.proto",
}
