// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/doc/doc.proto

package doc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDocRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       int64                  `protobuf:"varint,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDocRequest) Reset() {
	*x = CreateDocRequest{}
	mi := &file_proto_doc_doc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDocRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDocRequest) ProtoMessage() {}

func (x *CreateDocRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doc_doc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDocRequest.ProtoReflect.Descriptor instead.
func (*CreateDocRequest) Descriptor() ([]byte, []int) {
	return file_proto_doc_doc_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDocRequest) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *CreateDocRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type DocInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         string                 `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	OwnerId       int64                  `protobuf:"varint,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocInfo) Reset() {
	*x = DocInfo{}
	mi := &file_proto_doc_doc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocInfo) ProtoMessage() {}

func (x *DocInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doc_doc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocInfo.ProtoReflect.Descriptor instead.
func (*DocInfo) Descriptor() ([]byte, []int) {
	return file_proto_doc_doc_proto_rawDescGZIP(), []int{1}
}

func (x *DocInfo) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *DocInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DocInfo) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *DocInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *DocInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetDocRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         string                 `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocRequest) Reset() {
	*x = GetDocRequest{}
	mi := &file_proto_doc_doc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocRequest) ProtoMessage() {}

func (x *GetDocRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doc_doc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocRequest.ProtoReflect.Descriptor instead.
func (*GetDocRequest) Descriptor() ([]byte, []int) {
	return file_proto_doc_doc_proto_rawDescGZIP(), []int{2}
}

func (x *GetDocRequest) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

type DocDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         string                 `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	OwnerId       int64                  `protobuf:"varint,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Content       []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Collaborators []int64                `protobuf:"varint,7,rep,packed,name=collaborators,proto3" json:"collaborators,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocDetail) Reset() {
	*x = DocDetail{}
	mi := &file_proto_doc_doc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocDetail) ProtoMessage() {}

func (x *DocDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doc_doc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocDetail.ProtoReflect.Descriptor instead.
func (*DocDetail) Descriptor() ([]byte, []int) {
	return file_proto_doc_doc_proto_rawDescGZIP(), []int{3}
}

func (x *DocDetail) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *DocDetail) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DocDetail) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *DocDetail) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *DocDetail) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *DocDetail) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *DocDetail) GetCollaborators() []int64 {
	if x != nil {
		return x.Collaborators
	}
	return nil
}

type ListDocsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       int64                  `protobuf:"varint,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocsRequest) Reset() {
	*x = ListDocsRequest{}
	mi := &file_proto_doc_doc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocsRequest) ProtoMessage() {}

func (x *ListDocsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doc_doc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocsRequest.ProtoReflect.Descriptor instead.
func (*ListDocsRequest) Descriptor() ([]byte, []int) {
	return file_proto_doc_doc_proto_rawDescGZIP(), []int{4}
}

func (x *ListDocsRequest) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *ListDocsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDocsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListDocsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Docs          []*DocInfo             `protobuf:"bytes,1,rep,name=docs,proto3" json:"docs,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocsResponse) Reset() {
	*x = ListDocsResponse{}
	mi := &file_proto_doc_doc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocsResponse) ProtoMessage() {}

func (x *ListDocsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doc_doc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocsResponse.ProtoReflect.Descriptor instead.
func (*ListDocsResponse) Descriptor() ([]byte, []int) {
	return file_proto_doc_doc_proto_rawDescGZIP(), []int{5}
}

func (x *ListDocsResponse) GetDocs() []*DocInfo {
	if x != nil {
		return x.Docs
	}
	return nil
}

func (x *ListDocsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateDocRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         string                 `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDocRequest) Reset() {
	*x = UpdateDocRequest{}
	mi := &file_proto_doc_doc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDocRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDocRequest) ProtoMessage() {}

func (x *UpdateDocRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doc_doc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDocRequest.ProtoReflect.Descriptor instead.
func (*UpdateDocRequest) Descriptor() ([]byte, []int) {
	return file_proto_doc_doc_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateDocRequest) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *UpdateDocRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateDocRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateDocRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type DeleteDocRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         string                 `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocRequest) Reset() {
	*x = DeleteDocRequest{}
	mi := &file_proto_doc_doc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocRequest) ProtoMessage() {}

func (x *DeleteDocRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doc_doc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocRequest.ProtoReflect.Descriptor instead.
func (*DeleteDocRequest) Descriptor() ([]byte, []int) {
	return file_proto_doc_doc_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteDocRequest) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *DeleteDocRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DeleteDocResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocResponse) Reset() {
	*x = DeleteDocResponse{}
	mi := &file_proto_doc_doc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocResponse) ProtoMessage() {}

func (x *DeleteDocResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doc_doc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocResponse.ProtoReflect.Descriptor instead.
func (*DeleteDocResponse) Descriptor() ([]byte, []int) {
	return file_proto_doc_doc_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteDocResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UploadImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocId         string                 `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageRequest) Reset() {
	*x = UploadImageRequest{}
	mi := &file_proto_doc_doc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageRequest) ProtoMessage() {}

func (x *UploadImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doc_doc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageRequest.ProtoReflect.Descriptor instead.
func (*UploadImageRequest) Descriptor() ([]byte, []int) {
	return file_proto_doc_doc_proto_rawDescGZIP(), []int{9}
}

func (x *UploadImageRequest) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *UploadImageRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadImageRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadImageRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type UploadImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageResponse) Reset() {
	*x = UploadImageResponse{}
	mi := &file_proto_doc_doc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageResponse) ProtoMessage() {}

func (x *UploadImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doc_doc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageResponse.ProtoReflect.Descriptor instead.
func (*UploadImageResponse) Descriptor() ([]byte, []int) {
	return file_proto_doc_doc_proto_rawDescGZIP(), []int{10}
}

func (x *UploadImageResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ShareDocRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DocId          string                 `protobuf:"bytes,1,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	OwnerId        int64                  `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	CollaboratorId int64                  `protobuf:"varint,3,opt,name=collaborator_id,json=collaboratorId,proto3" json:"collaborator_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ShareDocRequest) Reset() {
	*x = ShareDocRequest{}
	mi := &file_proto_doc_doc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareDocRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareDocRequest) ProtoMessage() {}

func (x *ShareDocRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doc_doc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareDocRequest.ProtoReflect.Descriptor instead.
func (*ShareDocRequest) Descriptor() ([]byte, []int) {
	return file_proto_doc_doc_proto_rawDescGZIP(), []int{11}
}

func (x *ShareDocRequest) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *ShareDocRequest) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *ShareDocRequest) GetCollaboratorId() int64 {
	if x != nil {
		return x.CollaboratorId
	}
	return 0
}

type ShareDocResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareDocResponse) Reset() {
	*x = ShareDocResponse{}
	mi := &file_proto_doc_doc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareDocResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareDocResponse) ProtoMessage() {}

func (x *ShareDocResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doc_doc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareDocResponse.ProtoReflect.Descriptor instead.
func (*ShareDocResponse) Descriptor() ([]byte, []int) {
	return file_proto_doc_doc_proto_rawDescGZIP(), []int{12}
}

func (x *ShareDocResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_doc_doc_proto protoreflect.FileDescriptor

const file_proto_doc_doc_proto_rawDesc = "" +
	"\n" +
	"\x13proto/doc/doc.proto\x12\x03doc\"C\n" +
	"\x10CreateDocRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\x03R\aownerId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"\x8f\x01\n" +
	"\aDocInfo\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\tR\x05docId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\x03R\aownerId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\"&\n" +
	"\rGetDocRequest\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\tR\x05docId\"\xd1\x01\n" +
	"\tDocDetail\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\tR\x05docId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\x03R\aownerId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\x12$\n" +
	"\rcollaborators\x18\a \x03(\x03R\rcollaborators\"]\n" +
	"\x0fListDocsRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\x03R\aownerId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"J\n" +
	"\x10ListDocsResponse\x12 \n" +
	"\x04docs\x18\x01 \x03(\v2\f.doc.DocInfoR\x04docs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"r\n" +
	"\x10UpdateDocRequest\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\tR\x05docId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\"B\n" +
	"\x10DeleteDocRequest\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\tR\x05docId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"-\n" +
	"\x11DeleteDocResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"~\n" +
	"\x12UploadImageRequest\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\tR\x05docId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\"'\n" +
	"\x13UploadImageResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"l\n" +
	"\x0fShareDocRequest\x12\x15\n" +
	"\x06doc_id\x18\x01 \x01(\tR\x05docId\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\x03R\aownerId\x12'\n" +
	"\x0fcollaborator_id\x18\x03 \x01(\x03R\x0ecollaboratorId\",\n" +
	"\x10ShareDocResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x90\x03\n" +
	"\n" +
	"DocService\x120\n" +
	"\tCreateDoc\x12\x15.doc.CreateDocRequest\x1a\f.doc.DocInfo\x12,\n" +
	"\x06GetDoc\x12\x12.doc.GetDocRequest\x1a\x0e.doc.DocDetail\x127\n" +
	"\bListDocs\x12\x14.doc.ListDocsRequest\x1a\x15.doc.ListDocsResponse\x122\n" +
	"\tUpdateDoc\x12\x15.doc.UpdateDocRequest\x1a\x0e.doc.DocDetail\x12:\n" +
	"\tDeleteDoc\x12\x15.doc.DeleteDocRequest\x1a\x16.doc.DeleteDocResponse\x12@\n" +
	"\vUploadImage\x12\x17.doc.UploadImageRequest\x1a\x18.doc.UploadImageResponse\x127\n" +
	"\bShareDoc\x12\x14.doc.ShareDocRequest\x1a\x15.doc.ShareDocResponseB'Z%github.com/spike/goTogether/proto/docb\x06proto3"

var (
	file_proto_doc_doc_proto_rawDescOnce sync.Once
	file_proto_doc_doc_proto_rawDescData []byte
)

func file_proto_doc_doc_proto_rawDescGZIP() []byte {
	file_proto_doc_doc_proto_rawDescOnce.Do(func() {
		file_proto_doc_doc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_doc_doc_proto_rawDesc), len(file_proto_doc_doc_proto_rawDesc)))
	})
	return file_proto_doc_doc_proto_rawDescData
}

var file_proto_doc_doc_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_doc_doc_proto_goTypes = []any{
	(*CreateDocRequest)(nil),    // 0: doc.CreateDocRequest
	(*DocInfo)(nil),             // 1: doc.DocInfo
	(*GetDocRequest)(nil),       // 2: doc.GetDocRequest
	(*DocDetail)(nil),           // 3: doc.DocDetail
	(*ListDocsRequest)(nil),     // 4: doc.ListDocsRequest
	(*ListDocsResponse)(nil),    // 5: doc.ListDocsResponse
	(*UpdateDocRequest)(nil),    // 6: doc.UpdateDocRequest
	(*DeleteDocRequest)(nil),    // 7: doc.DeleteDocRequest
	(*DeleteDocResponse)(nil),   // 8: doc.DeleteDocResponse
	(*UploadImageRequest)(nil),  // 9: doc.UploadImageRequest
	(*UploadImageResponse)(nil), // 10: doc.UploadImageResponse
	(*ShareDocRequest)(nil),     // 11: doc.ShareDocRequest
	(*ShareDocResponse)(nil),    // 12: doc.ShareDocResponse
}
var file_proto_doc_doc_proto_depIdxs = []int32{
	1,  // 0: doc.ListDocsResponse.docs:type_name -> doc.DocInfo
	0,  // 1: doc.DocService.CreateDoc:input_type -> doc.CreateDocRequest
	2,  // 2: doc.DocService.GetDoc:input_type -> doc.GetDocRequest
	4,  // 3: doc.DocService.ListDocs:input_type -> doc.ListDocsRequest
	6,  // 4: doc.DocService.UpdateDoc:input_type -> doc.UpdateDocRequest
	7,  // 5: doc.DocService.DeleteDoc:input_type -> doc.DeleteDocRequest
	9,  // 6: doc.DocService.UploadImage:input_type -> doc.UploadImageRequest
	11, // 7: doc.DocService.ShareDoc:input_type -> doc.ShareDocRequest
	1,  // 8: doc.DocService.CreateDoc:output_type -> doc.DocInfo
	3,  // 9: doc.DocService.GetDoc:output_type -> doc.DocDetail
	5,  // 10: doc.DocService.ListDocs:output_type -> doc.ListDocsResponse
	3,  // 11: doc.DocService.UpdateDoc:output_type -> doc.DocDetail
	8,  // 12: doc.DocService.DeleteDoc:output_type -> doc.DeleteDocResponse
	10, // 13: doc.DocService.UploadImage:output_type -> doc.UploadImageResponse
	12, // 14: doc.DocService.ShareDoc:output_type -> doc.ShareDocResponse
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_doc_doc_proto_init() }
func file_proto_doc_doc_proto_init() {
	if File_proto_doc_doc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_doc_doc_proto_rawDesc), len(file_proto_doc_doc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_doc_doc_proto_goTypes,
		DependencyIndexes: file_proto_doc_doc_proto_depIdxs,
		MessageInfos:      file_proto_doc_doc_proto_msgTypes,
	}.Build()
	File_proto_doc_doc_proto = out.File
	file_proto_doc_doc_proto_goTypes = nil
	file_proto_doc_doc_proto_depIdxs = nil
}
