// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/doc/doc.proto

package doc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DocService_CreateDoc_FullMethodName   = "/doc.DocService/CreateDoc"
	DocService_GetDoc_FullMethodName      = "/doc.DocService/GetDoc"
	DocService_ListDocs_FullMethodName    = "/doc.DocService/ListDocs"
	DocService_UpdateDoc_FullMethodName   = "/doc.DocService/UpdateDoc"
	DocService_DeleteDoc_FullMethodName   = "/doc.DocService/DeleteDoc"
	DocService_UploadImage_FullMethodName = "/doc.DocService/UploadImage"
	DocService_ShareDoc_FullMethodName    = "/doc.DocService/ShareDoc"
)

// DocServiceClient is the client API for DocService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocServiceClient interface {
	CreateDoc(ctx context.Context, in *CreateDocRequest, opts ...grpc.CallOption) (*DocInfo, error)
	GetDoc(ctx context.Context, in *GetDocRequest, opts ...grpc.CallOption) (*DocDetail, error)
	ListDocs(ctx context.Context, in *ListDocsRequest, opts ...grpc.CallOption) (*ListDocsResponse, error)
	UpdateDoc(ctx context.Context, in *UpdateDocRequest, opts ...grpc.CallOption) (*DocDetail, error)
	DeleteDoc(ctx context.Context, in *DeleteDocRequest, opts ...grpc.CallOption) (*DeleteDocResponse, error)
	UploadImage(ctx context.Context, in *UploadImageRequest, opts ...grpc.CallOption) (*UploadImageResponse, error)
	ShareDoc(ctx context.Context, in *ShareDocRequest, opts ...grpc.CallOption) (*ShareDocResponse, error)
}

type docServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDocServiceClient(cc grpc.ClientConnInterface) DocServiceClient {
	return &docServiceClient{cc}
}

func (c *docServiceClient) CreateDoc(ctx context.Context, in *CreateDocRequest, opts ...grpc.CallOption) (*DocInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocInfo)
	err := c.cc.Invoke(ctx, DocService_CreateDoc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *docServiceClient) GetDoc(ctx context.Context, in *GetDocRequest, opts ...grpc.CallOption) (*DocDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocDetail)
	err := c.cc.Invoke(ctx, DocService_GetDoc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *docServiceClient) ListDocs(ctx context.Context, in *ListDocsRequest, opts ...grpc.CallOption) (*ListDocsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDocsResponse)
	err := c.cc.Invoke(ctx, DocService_ListDocs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *docServiceClient) UpdateDoc(ctx context.Context, in *UpdateDocRequest, opts ...grpc.CallOption) (*DocDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocDetail)
	err := c.cc.Invoke(ctx, DocService_UpdateDoc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *docServiceClient) DeleteDoc(ctx context.Context, in *DeleteDocRequest, opts ...grpc.CallOption) (*DeleteDocResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDocResponse)
	err := c.cc.Invoke(ctx, DocService_DeleteDoc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *docServiceClient) UploadImage(ctx context.Context, in *UploadImageRequest, opts ...grpc.CallOption) (*UploadImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadImageResponse)
	err := c.cc.Invoke(ctx, DocService_UploadImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *docServiceClient) ShareDoc(ctx context.Context, in *ShareDocRequest, opts ...grpc.CallOption) (*ShareDocResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShareDocResponse)
	err := c.cc.Invoke(ctx, DocService_ShareDoc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocServiceServer is the server API for DocService service.
// All implementations must embed UnimplementedDocServiceServer
// for forward compatibility.
type DocServiceServer interface {
	CreateDoc(context.Context, *CreateDocRequest) (*DocInfo, error)
	GetDoc(context.Context, *GetDocRequest) (*DocDetail, error)
	ListDocs(context.Context, *ListDocsRequest) (*ListDocsResponse, error)
	UpdateDoc(context.Context, *UpdateDocRequest) (*DocDetail, error)
	DeleteDoc(context.Context, *DeleteDocRequest) (*DeleteDocResponse, error)
	UploadImage(context.Context, *UploadImageRequest) (*UploadImageResponse, error)
	ShareDoc(context.Context, *ShareDocRequest) (*ShareDocResponse, error)
	mustEmbedUnimplementedDocServiceServer()
}

// UnimplementedDocServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocServiceServer struct{}

func (UnimplementedDocServiceServer) CreateDoc(context.Context, *CreateDocRequest) (*DocInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDoc not implemented")
}
func (UnimplementedDocServiceServer) GetDoc(context.Context, *GetDocRequest) (*DocDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDoc not implemented")
}
func (UnimplementedDocServiceServer) ListDocs(context.Context, *ListDocsRequest) (*ListDocsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDocs not implemented")
}
func (UnimplementedDocServiceServer) UpdateDoc(context.Context, *UpdateDocRequest) (*DocDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDoc not implemented")
}
func (UnimplementedDocServiceServer) DeleteDoc(context.Context, *DeleteDocRequest) (*DeleteDocResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDoc not implemented")
}
func (UnimplementedDocServiceServer) UploadImage(context.Context, *UploadImageRequest) (*UploadImageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadImage not implemented")
}
func (UnimplementedDocServiceServer) ShareDoc(context.Context, *ShareDocRequest) (*ShareDocResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ShareDoc not implemented")
}
func (UnimplementedDocServiceServer) mustEmbedUnimplementedDocServiceServer() {}
func (UnimplementedDocServiceServer) testEmbeddedByValue()                    {}

// UnsafeDocServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocServiceServer will
// result in compilation errors.
type UnsafeDocServiceServer interface {
	mustEmbedUnimplementedDocServiceServer()
}

func RegisterDocServiceServer(s grpc.ServiceRegistrar, srv DocServiceServer) {
	// If the following call panics, it indicates UnimplementedDocServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DocService_ServiceDesc, srv)
}

func _DocService_CreateDoc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDocRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocServiceServer).CreateDoc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocService_CreateDoc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocServiceServer).CreateDoc(ctx, req.(*CreateDocRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocService_GetDoc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocServiceServer).GetDoc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocService_GetDoc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocServiceServer).GetDoc(ctx, req.(*GetDocRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocService_ListDocs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDocsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocServiceServer).ListDocs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocService_ListDocs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocServiceServer).ListDocs(ctx, req.(*ListDocsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocService_UpdateDoc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDocRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocServiceServer).UpdateDoc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocService_UpdateDoc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocServiceServer).UpdateDoc(ctx, req.(*UpdateDocRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocService_DeleteDoc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDocRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocServiceServer).DeleteDoc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocService_DeleteDoc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocServiceServer).DeleteDoc(ctx, req.(*DeleteDocRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocService_UploadImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocServiceServer).UploadImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocService_UploadImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocServiceServer).UploadImage(ctx, req.(*UploadImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocService_ShareDoc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareDocRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocServiceServer).ShareDoc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocService_ShareDoc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocServiceServer).ShareDoc(ctx, req.(*ShareDocRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DocService_ServiceDesc is the grpc.ServiceDesc for DocService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "doc.DocService",
	HandlerType: (*DocServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDoc",
			Handler:    _DocService_CreateDoc_Handler,
		},
		{
			MethodName: "GetDoc",
			Handler:    _DocService_GetDoc_Handler,
		},
		{
			MethodName: "ListDocs",
			Handler:    _DocService_ListDocs_Handler,
		},
		{
			MethodName: "UpdateDoc",
			Handler:    _DocService_UpdateDoc_Handler,
		},
		{
			MethodName: "DeleteDoc",
			Handler:    _DocService_DeleteDoc_Handler,
		},
		{
			MethodName: "UploadImage",
			Handler:    _DocService_UploadImage_Handler,
		},
		{
			MethodName: "ShareDoc",
			Handler:    _DocService_ShareDoc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/doc/doc.proto",
}
