global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8080']
  - job_name: 'collab-service'
    static_configs:
      - targets: ['collab-service:8082']
  - job_name: 'doc-service'
    static_configs:
      - targets: ['doc-service:9102']
